name: Documentation Check

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'docs/**'
      - 'src/**'
      - 'agent/**'
      - '*.md'
      - '*.rst'

jobs:
  docs-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        pip install doc8 restructuredtext-lint
        
    - name: Install Node.js dependencies
      run: |
        npm install
        npm install -g frida-compile typescript
        
    - name: Compile TypeScript hooks
      run: |
        npm run build
        
    - name: Check reStructuredText syntax
      run: |
        find docs -name "*.rst" -exec rst-lint {} \;
        
    - name: Check documentation style
      run: |
        doc8 docs --max-line-length 120
        
    - name: Build documentation (check for errors)
      run: |
        cd docs
        make html SPHINXOPTS="-W --keep-going"
        
    - name: Check for broken internal links
      run: |
        cd docs
        make linkcheck
        
    - name: Upload documentation preview
      uses: actions/upload-artifact@v3
      with:
        name: docs-preview
        path: docs/_build/html/
        retention-days: 7
        
    - name: Comment PR with documentation preview
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const runId = context.runId;
          
          const comment = `📚 **Documentation Preview**
          
          The documentation has been built successfully for this PR.
          
          🔗 **Download preview**: [Documentation Artifacts](https://github.com/${owner}/${repo}/actions/runs/${runId})
          
          📋 **Changes detected in:**
          - Documentation files (\`docs/\`)
          - Source code (\`src/\`, \`agent/\`)
          
          ✅ **Documentation checks passed:**
          - reStructuredText syntax validation
          - Sphinx build without errors
          - Internal link validation
          - Style guide compliance
          
          To view the documentation locally:
          \`\`\`bash
          cd docs
          make html
          open _build/html/index.html
          \`\`\``;
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: comment
          });