# .github/workflows/lint.yml
name: Ruff

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      # 1 Fetch the code
      - uses: actions/checkout@v4

      # 2 Install Python 3.11 (same as the docs snippet)
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3 Install Ruff (and pip upgrade, exactly like the docs)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # 4 Run Ruff with GitHub‑annotations output
      - name: Run Ruff
        run: ruff check --output-format=github .
